package com.butler.app

import android.content.Intent
import android.os.Bundle
import android.view.View
import android.view.WindowManager
import android.webkit.JavascriptInterface
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.appcompat.app.AppCompatActivity
import androidx.webkit.WebViewAssetLoader
import com.chaquo.python.Python
import com.chaquo.python.PyObject
import android.util.Log
import org.json.JSONObject
import java.io.File

// Import the Go-Mobile mobile package (generated by gomobile bind)
import mobile.Mobile
import mobile.Runner
import mobile.ButlerEventListener

class MainActivity : AppCompatActivity() {

    private lateinit var webView: WebView
    private var butlerModule: PyObject? = null
    private lateinit var assetLoader: WebViewAssetLoader
    private var kernelRunner: Runner? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // 1. Force Hardware Acceleration
        window.setFlags(
            WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED,
            WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED
        )

        // Start Foreground Service
        val serviceIntent = Intent(this, ButlerForegroundService::class.java)
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
            startForegroundService(serviceIntent)
        } else {
            startService(serviceIntent)
        }

        // Initialize Python & SkillManager
        val py = Python.getInstance()
        butlerModule = py.getModule("butler_android")
        butlerModule?.callAttr("initialize", filesDir.absolutePath)

        // Setup Asset Loader
        assetLoader = WebViewAssetLoader.Builder()
            .addPathHandler("/assets/", WebViewAssetLoader.AssetsPathHandler(this))
            .addPathHandler("/skills/", WebViewAssetLoader.InternalStoragePathHandler(this, File(filesDir, "skills")))
            .build()

        // Setup WebView
        webView = WebView(this)
        setContentView(webView)
        webView.setLayerType(View.LAYER_TYPE_HARDWARE, null)

        val settings = webView.settings
        settings.javaScriptEnabled = true
        settings.domStorageEnabled = true
        settings.allowFileAccess = true

        webView.addJavascriptInterface(ButlerNativeBridge(), "ButlerNativeBridge")

        webView.webViewClient = object : WebViewClient() {
            override fun shouldInterceptRequest(view: WebView?, request: WebResourceRequest): WebResourceResponse? {
                return assetLoader.shouldInterceptRequest(request.url)
            }
        }

        // 2. Initialize and Start Go-Mobile Kernel
        startGoKernel()

        webView.loadUrl("https://appassets.androidplatform.net/assets/www/index.html")
    }

    private fun startGoKernel() {
        try {
            kernelRunner = Mobile.newRunner()

            val config = JSONObject().apply {
                put("server_url", "ws://192.168.1.100:8000/ws/butler") // Example config
                put("token", "BUTLER_SECRET_2026")
                put("id", "android_node_" + android.os.Build.MODEL)
            }

            kernelRunner?.start(config.toString(), object : ButlerEventListener {
                override fun OnStatusUpdate(status: String) {
                    Log.i("ButlerKernel", "Status: $status")
                }

                override fun OnLog(message: String) {
                    Log.d("ButlerKernel", "Log: $message")
                }

                override fun OnMetricsUpdate(jsonMetrics: String) {
                    // High-frequency injection to WebView
                    runOnUiThread {
                        webView.evaluateJavascript("if(window.StateMatrix) window.StateMatrix.updateFromBackend($jsonMetrics);", null)
                    }
                }

                override fun OnDrasStateChanged(cpuUsage: Double, throttleActive: Boolean) {
                    Log.w("ButlerKernel", "DRAS State: CPU=$cpuUsage, Throttle=$throttleActive")
                }

                override fun OnClusterDiscovered(deviceName: String, ipAddress: String) {
                    Log.i("ButlerKernel", "Discovered Node: $deviceName at $ipAddress")
                }
            })
            Log.i("MainActivity", "Go Kernel Started Successfully")
        } catch (e: Exception) {
            Log.e("MainActivity", "Failed to start Go Kernel: ${e.message}")
        }
    }

    inner class ButlerNativeBridge {
        @JavascriptInterface
        fun triggerWormholeTransfer(assetId: String, targetX: Int, targetY: Int) {
            // Logic to forward to Go Kernel via runner methods if needed
            Log.d("ButlerBridge", "Wormhole Triggered for $assetId")
        }

        @JavascriptInterface
        fun callSkill(skillId: String, action: String, paramsJson: String) {
            butlerModule?.callAttr("call_plugin", skillId, action, paramsJson)
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        kernelRunner?.stop()
        butlerModule?.callAttr("cleanup")
    }
}
