package converter

import (
	"bytes"
	"context"
	"fmt"
	"io"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
)

type MarkdownToHTMLConverter struct{}

func (c *MarkdownToHTMLConverter) SupportedFormats() (DocType, DocType) {
	return TypeMarkdown, TypeHTML
}

func (c *MarkdownToHTMLConverter) Convert(ctx context.Context, src io.Reader, dst io.Writer, opts ConvertOptions) error {
	// 1. Read Markdown source
	var buf bytes.Buffer
	if _, err := io.Copy(&buf, src); err != nil {
		return fmt.Errorf("failed to read markdown source: %w", err)
	}

	// 2. Configure Goldmark parser with extensions
	md := goldmark.New(
		goldmark.WithExtensions(
			extension.GFM,
			extension.DefinitionList,
		),
		goldmark.WithParserOptions(
			parser.WithAutoHeadingID(),
		),
	)

	// 3. Render HTML and inject premium Butler CSS theme and footer
	theme := "default"
	if opts.Theme != "" {
		theme = opts.Theme
	}

	htmlHeader := fmt.Sprintf(`<!DOCTYPE html>
<html data-theme="%s">
<head>
<meta charset="UTF-8">
<style>
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 2rem; background: var(--bg-color, #ffffff); color: var(--text-color, #333333); line-height: 1.6; }
.butler-content { max-width: 800px; margin: 0 auto; }
.butler-footer { text-align: center; margin-top: 3rem; font-size: 0.85rem; color: #888888; border-top: 1px solid #eaeaea; padding-top: 1.5rem; }
pre { background: #f6f8fa; padding: 1rem; border-radius: 6px; overflow-x: auto; }
code { font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; font-size: 0.85em; }
table { border-collapse: collapse; width: 100%%; margin: 1.5rem 0; }
th, td { border: 1px solid #eaeaea; padding: 8px 12px; text-align: left; }
th { background-color: #f6f8fa; }
</style>
</head>
<body>
<div class="butler-content">`, theme)

	if _, err := dst.Write([]byte(htmlHeader)); err != nil {
		return err
	}

	if err := md.Convert(buf.Bytes(), dst); err != nil {
		return fmt.Errorf("markdown conversion logic failed: %w", err)
	}

	footerText := "Generated by Butler Automation Service"
	if opts.WithWater {
		footerText = "Generated by Butler Automation Service | Secure Watermarked Document"
	}
	htmlFooter := fmt.Sprintf(`</div><footer class="butler-footer">%s</footer></body></html>`, footerText)

	if _, err := dst.Write([]byte(htmlFooter)); err != nil {
		return err
	}

	return nil
}
